### ISSUE TITLE
Blank first question / answer

### ISSUE THREAD

**Issue by freshwaterwest** [josht/faqMan#26]
I've noticed on my install that faqman seems to be adding an empty question / answer pair first

The reason I noticed is that I added a + sign with css to show the questions and have collapsible answers:
.faqman-question:before {
    content: "+";margin-right:10px;
}

**Comment by jspaans91** [comment]
Hi,

I have this problem also. It seems like that this code in the snippet is the problem:
```
 if (isset($setHeading)) {
        $list[] = $setHeading . "\n" . implode($outputSeparator, $setList);
    } else {
        $list[] = implode($outputSeparator, $setList);

    }
```
When I only set the line below in the snippet, the empty question/answer is gone.

```
$list[] = implode($outputSeparator, $setList);
```

**Comment by josht** [comment]
So 5 years later... this is happening from wrong default property set on the snippet. You'll want to update the `setTpl` property to either an empty value or `settpl`.
This is supposed to handle displaying Name/Description info for each set of FAQ's but has wrongly been set to use the default `Faq` template and so outputs a blank entry instead of the expected header.
Going forward the default property will be set correctly. Sorry about the problem and confusion.
