### ISSUE TITLE
Getting extra divs before the main loop

### ISSUE THREAD

**Issue by rv-solutions** [josht/faqMan#43]
I've set my own TPL which loops through my entries correctly, but I'm getting one set of the default

`<div class="faqman-question"></div>
<span class="faqman-answer"></span>`

 tpl placed before mine in the html. Might just be me being stupid... Thanks!

**Comment by josht** [comment]
This is happening from a wrong default property set on the snippet. You'll want to update the `setTpl` property to either an empty value or `settpl`.
This property is supposed to handle displaying Name/Description info for each set of FAQ's but has wrongly been set to use the default `Faq` template and so outputs a blank entry instead of the expected header.
Going forward the default property will be set correctly. Sorry about the problem and confusion.
